services:
  wync-app:
    build:
      context: .          # root folder, includes all projects
      dockerfile: Api/Dockerfile  # Dockerfile inside Api folder
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo
    networks:
      - wync-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wync-net

volumes:
  mongo-data:

networks:
  wync-net:
