services:
  wync-api:
    container_name: wync-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "18080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://0.0.0.0:8080
    depends_on:
      - wync-mongo
    networks:
      - wync-network

  wync-mongo:
    container_name: wync-mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wync-network

volumes:
  mongo-data:

networks:
  wync-network:
    name: wync-network